# Generated by Django 3.2.12 on 2023-04-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('availability', models.IntegerField()),
                ('cost', models.FloatField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
