# Generated by Django 3.2.12 on 2023-04-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment pending', 'Payment_pending'), ('Payment done', 'Payment_done')], default='Payment pending', max_length=100),
        ),
    ]
