# Generated by Django 3.2.12 on 2023-04-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Payment transaction-id not submitted', 'Payment transaction-id not submitted'), ('Payment verification pending', 'Payment verification pending'), ('Payment not received', 'Payment not received'), ('Payment verification done', 'Payment verification done'), ('Delivered', 'Delivered')], default='Payment verification pending', max_length=100),
        ),
    ]
